
title: CHAKRA Ontology
author:
  name: Nicholas Harley
  email: nicholas.harley@vub.be

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  n-harley

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-jupyter-notebook
relative_links:
  enabled: true
  collections: true

show_downloads: "true"  
